---
name: aio-toolbox build
on:
  merge_group:
  push:
    branches:
      - "main"
    paths:
      - "src/aio/**"
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - "main"
    paths:
      - "src/aio/**"
  workflow_dispatch:
jobs:
  build-toolbox:
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    uses: ixxeL-DevOps/gha-templates/.github/workflows/docker-build.yaml@main
    with:
      component: aio
      workingdir: src/aio
      img-name: toolbox
      registry-username: ${{ vars.DOCKER_HUB_USER }}
    secrets: inherit
