---
name: arc-runner build
on:
  merge_group:
  push:
    branches:
      - "main"
    paths:
      - "src/arc/**"
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - "main"
    paths:
      - "src/arc/**"
  workflow_dispatch:
jobs:
  arc-runner:
    uses: ixxeL-DevOps/gha-templates/.github/workflows/docker-build.yaml@main
    with:
      component: arc
      workingdir: src/arc
      img-name: toolbox
      registry-username: ${{ vars.DOCKER_HUB_USER }}
    secrets: inherit
