---
name: builder-toolbox build
on:
  schedule:
    - cron: 0 1 * * 1
  push:
    branches:
      - "main"
    paths:
      - "src/builder/**"
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - "main"
    paths:
      - "src/builder/**"
  workflow_dispatch:
jobs:
  builder-toolbox:
    uses: ixxeL-DevOps/gha-templates/.github/workflows/docker-build.yaml@main
    with:
      component: builder
      workingdir: src/builder
      img-name: toolbox
      registry-username: ${{ vars.DOCKER_HUB_USER }}
    secrets: inherit
      # git-token: ${{ secrets.PAT }}
      # DOCKER_IO_PWD: ${{ secrets.DOCKER_IO_PWD }}
