---
name: certs-toolbox build
on:
  schedule:
    - cron: 0 1 * * 1
  push:
    branches:
      - "main"
    paths:
      - "src/certs/**"
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - "main"
    paths:
      - "src/certs/**"
  workflow_dispatch:
jobs:
  build:
    uses: ixxeL-DevOps/gha-templates/.github/workflows/docker-build.yaml@main
    with:
      component: certs
      workingdir: src/certs
      img-name: toolbox
      registry-username: ${{ vars.DOCKER_HUB_USER }}
    secrets: inherit
      # git-token: ${{ secrets.PAT }}
      # DOCKER_IO_PWD: ${{ secrets.DOCKER_IO_PWD }}
