---
name: certs-toolbox build
on:
  push:
    branches:
      - "main"
    paths:
      - "src/certs/**"
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - "main"
    paths:
      - "src/certs/**"
  workflow_dispatch:
jobs:
  certs-toolbox:
    uses: ixxeL-DevOps/gha-templates/.github/workflows/docker-build.yaml@main
    with:
      component: certs
      workingdir: src/certs
      img-name: toolbox
      registry-username: ${{ vars.DOCKER_HUB_USER }}
    secrets:
      git-token: ${{ secrets.PAT }}
      DOCKER_IO_PWD: ${{ secrets.DOCKER_IO_PWD }}
