---
name: ci-toolbox build
on:
  schedule:
    - cron: 0 1 * * 1
  push:
    branches:
      - "main"
    paths:
      - "src/ci/**"
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - "main"
    paths:
      - "src/ci/**"
  workflow_dispatch:
jobs:
  ci-toolbox:
    uses: ixxeL-DevOps/gha-templates/.github/workflows/docker-build.yaml@main
    with:
      component: ci
      workingdir: src/ci
      img-name: toolbox
      registry-username: ${{ vars.DOCKER_HUB_USER }}
    secrets:
      git-token: ${{ secrets.PAT }}
      DOCKER_IO_PWD: ${{ secrets.DOCKER_IO_PWD }}
