---
name: ci-toolbox build
on:
  merge_group:
  push:
    branches:
      - "main"
    paths:
      - "src/ci/**"
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - "main"
    paths:
      - "src/ci/**"
  workflow_dispatch:
jobs:
  build-toolbox:
    uses: ixxeL-DevOps/gha-templates/.github/workflows/docker-build.yaml@main
    with:
      component: ci
      workingdir: src/ci
      img-name: toolbox
      registry-username: ${{ vars.DOCKER_HUB_USER }}
    secrets: inherit
