---
name: helm-toolbox build
on:
  merge_group:
  push:
    branches:
      - "main"
    paths:
      - "src/helm/**"
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - "main"
    paths:
      - "src/helm/**"
  workflow_dispatch:
jobs:
  helm-toolbox:
    uses: ixxeL-DevOps/gha-templates/.github/workflows/docker-build.yaml@main
    with:
      component: helm
      workingdir: src/helm
      img-name: toolbox
      registry-username: ${{ vars.DOCKER_HUB_USER }}
    secrets: inherit
