---
name: Release docker image
on:
  workflow_dispatch:
    inputs:
      component:
        required: true
        type: choice
        options:
          - "base"
          - "arc"
          - "builder"
          - "aio"
          - "cd"
          - "certs"
          - "ci"
          - "helm"
        default: "base"
        description: Image to release
      release-type:
        required: true
        type: choice
        options:
          - "GA"
          - "RC"
        default: "GA"
        description: General Availability or Release Candidate
jobs:
  release-img:
    uses: ixxeL-DevOps/gha-templates/.github/workflows/__docker-release__.yaml@main
    with:
      component: ${{ inputs.component }}
      workingdir: src/${{ inputs.component }}
      img-name: toolbox
      cache-registry: docker.io/ixxel
      registry-url: docker.io
      registry-username: ${{ vars.DOCKER_HUB_USER }}
      publish: "true"
      prerelease: "${{ inputs.release-type == 'RC' }}"
    secrets:
      git-token: ${{ secrets.PAT }}
      registry-password: ${{ secrets.DOCKER_IO_PWD }}
