---
name: Release docker image
on:
  workflow_dispatch:
    inputs:
      component:
        required: true
        type: choice
        options:
          - "base"
          - "builder"
          - "aio"
          - "cd"
          - "certs"
          - "ci"
          - "helm"
        default: "base"
        description: Image to release
jobs:
  retag-img:
    uses: ixxeL-DevOps/gha-templates/.github/workflows/__docker-release__.yaml@main
    with:
      component: ${{ inputs.component }}
      workingdir: src/${{ inputs.component }}
      img-name: toolbox
      registry-url: docker.io
      registry-username: ${{ vars.DOCKER_HUB_USER }}
    secrets:
      git-token: ${{ secrets.PAT }}
      registry-password: ${{ secrets.DOCKER_IO_PWD }}
