---
name: Release docker image
on:
  push:
    tags: "*"
jobs:
  retag-img:
    uses: ixxeL-DevOps/gha-templates/.github/workflows/__release__.yaml@main
    secrets:
      git-token: ${{ secrets.PAT }}
